# Generated by Django 4.1.6 on 2023-08-23 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mails',
            old_name='messsage',
            new_name='message',
        ),
    ]
